import * as React from "react";

import Head from "next/head";
import Header from "../components/Header";

import "tailwindcss/tailwind.css";

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Next with Tailwind</title>
				<meta
					name="description"
					content="Generated by create next app with tailwind css"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<Header />
			</header>
			<main className="md:container md:mx-auto mt-10 px-4">
				<Component {...pageProps} />
			</main>
		</>
	);
}

export default MyApp;
