import * as React from "react";

import Head from "next/head";
import Header from "../components/Header";

import "styles/globals.css";
import "tailwindcss/tailwind.css";

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Next with Tailwind</title>
				<meta
					name="description"
					content="Generated by create next app with tailwind css"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="md:container md:mx-auto px-3 md:px-0 py-5 h-screen">
				<Component {...pageProps} />
			</main>
		</>
	);
}

export default MyApp;
